apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: allforone
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: catalog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3003
              hostPort: 3003
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: allforone
  labels:
    app: catalog
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
    - name: http
      port: 3003
      targetPort: 3003
