apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: allforone
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3002
              hostPort: 3002
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: allforone
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: http
      port: 3002
      targetPort: 3002
